# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jeremy Neal
tagline:             'Software Developer'
description:         "I'm a Baltimore-based software developer. I love programming in Ruby and Python mainly, though I always try to learn new skills."
url:                 http://sdroadie.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jeremy Neal
  twitter:           https://twitter.com/@_jneal_
  github:            https://github.com/sdroadie
  email:             jneal1992@gmail.com

# Custom vars
version:             1.0.0
