# Site settings
title: sdroadie.github.io
email: jneal1992@gmail.com
description: "Homepage of Jeremy Neal. I make software. I'd like to get paid for it."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Jeremy Neal
  location: Baltimore
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sdroadie92
  - title: bitbucket 
    url: http://bitbucket.org/jeremy_neal
  - title: github
    url: http://github.com/sdroadie

# Postal address (add as many lines as necessary)
address:
  - line: 111 Edelton Avenue
  - line: Severn, MD 21144
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
